Here's the content formatted for a single Jupyter Notebook cell:

```python
# Q1. What is a database? Differentiate between SQL and NoSQL databases.
"""
A database is a systematic collection of data that can be easily accessed, managed, and updated. It is used to store and retrieve data efficiently.

Differences between SQL and NoSQL databases:

1. SQL Databases:
   - Use Structured Query Language (SQL) for defining and manipulating data.
   - Have a fixed schema and support complex queries.
   - Examples: MySQL, PostgreSQL, SQLite.

2. NoSQL Databases:
   - Use various data models such as document, key-value, column-family, or graph.
   - Schema-less or flexible schema, suitable for unstructured data.
   - Examples: MongoDB, Cassandra, Redis.
"""

# Q2. What is DDL? Explain why CREATE, DROP, ALTER, and TRUNCATE are used with an example.
"""
DDL (Data Definition Language) is used to define and manage the structure of database objects.

1. CREATE: Used to create a new database object such as a table.
   Example: `CREATE TABLE students (id INT PRIMARY KEY, name VARCHAR(100));`

2. DROP: Used to delete an existing database object.
   Example: `DROP TABLE students;`

3. ALTER: Used to modify an existing database object.
   Example: `ALTER TABLE students ADD COLUMN age INT;`

4. TRUNCATE: Used to remove all records from a table, but keeps the table structure.
   Example: `TRUNCATE TABLE students;`
"""

# Q3. What is DML? Explain INSERT, UPDATE, and DELETE with an example.
"""
DML (Data Manipulation Language) is used to manipulate and manage data within database objects.

1. INSERT: Adds new records to a table.
   Example: `INSERT INTO students (id, name) VALUES (1, 'John Doe');`

2. UPDATE: Modifies existing records in a table.
   Example: `UPDATE students SET name = 'Jane Doe' WHERE id = 1;`

3. DELETE: Removes records from a table.
   Example: `DELETE FROM students WHERE id = 1;`
"""

# Q4. What is DQL? Explain SELECT with an example.
"""
DQL (Data Query Language) is used to query and retrieve data from a database.

1. SELECT: Retrieves data from a table.
   Example: `SELECT * FROM students;`
"""

# Q5. Explain Primary Key and Foreign Key.
"""
1. Primary Key:
   - A unique identifier for each record in a table.
   - Ensures that no two records have the same primary key value.
   - Example: `id` column in a `students` table.

2. Foreign Key:
   - A field (or collection of fields) in one table that uniquely identifies a row in another table.
   - Establishes and enforces a link between the two tables.
   - Example: `student_id` in a `grades` table that references the `id` column in the `students` table.
"""

# Q6. Write a Python code to connect MySQL to Python. Explain the cursor() and execute() method.
"""
import mysql.connector

# Establishing the connection
conn = mysql.connector.connect(
    host="localhost",
    user="your_username",
    password="your_password",
    database="your_database"
)

# Creating a cursor object
cursor = conn.cursor()

# Executing an SQL query
cursor.execute("SELECT * FROM students;")

# Fetching the results
results = cursor.fetchall()
for row in results:
    print(row)

# Closing the connection
conn.close()
"""
"""
The `cursor()` method creates a cursor object which is used to interact with the database. The `execute()` method runs SQL queries using this cursor. After executing a query, you can fetch results using methods like `fetchall()`, `fetchone()`, or `fetchmany()`.
"""

# Q7. Give the order of execution of SQL clauses in an SQL query.
"""
The order of execution of SQL clauses is as follows:

1. `FROM`: Specifies the tables to retrieve data from.
2. `JOIN`: Joins tables based on conditions.
3. `ON`: Specifies the conditions for joining tables.
4. `WHERE`: Filters records based on a condition.
5. `GROUP BY`: Groups records based on specified columns.
6. `HAVING`: Filters groups based on a condition.
7. `SELECT`: Specifies the columns to retrieve.
8. `DISTINCT`: Removes duplicate rows from the results.
9. `ORDER BY`: Sorts the results based on specified columns.
10. `LIMIT`: Limits the number of rows returned by the query.
"""
```